### ISSUE TITLE
Data writing to wrong database

### ISSUE THREAD

**Issue by natstar93** [makersacademy/slack-overflow#39] opened 2015-07-03 14:18 UTC
Hi,

My data is writing to the development database when I run a test. The repo is here: https://github.com/natstar93/chitter-challenge  but the part that seems to be going wrong is:

spec_helper.rb
```
require './app/models/user'
require './datamapper_setup'

ENV['RACK_ENV'] = 'test'
require File.join(File.dirname(__FILE__), '..', 'app/chitter.rb')

```
datamapper_setup.rb
```
env = ENV['RACK_ENV'] || 'development'
DataMapper.setup(:default, "postgres://localhost/chitter_#{env}")
```
When I hard code 'test' into the above it works, so I guess datamapper_setup isn't being required properly.
Database names are chitter_test and chitter_development

Nat

**Comment by ptolemybarnes** [comment] 2015-07-03 14:20
The problem is with the order in which things are happening You want ENV['RACK_ENV'] to be defined as 'test' *before* the code in data_mapper.rb executes. ;-)

**Comment by natstar93** [comment] 2015-07-03 14:20
I realised that the code in spec_helper was in the wrong order. The ENV must be set before datamapper_setup is called:

```
ENV['RACK_ENV'] = 'test'
require File.join(File.dirname(__FILE__), '..', 'app/chitter.rb')
require './app/models/user'
require './datamapper_setup'
```

**Comment by tansaku** [comment] 2015-07-03 14:47
good show @natstar93  shall we close this then?

**Closed** 2015-07-03 14:49 UTC
