### ISSUE TITLE
Changing plane states

### ISSUE THREAD

**Issue by Jeremy-Barrass** [makersacademy/slack-overflow#162] opened 2016-01-24 20:57 UTC
So, I've got two user stories to go, which will be easy to implement, so I figure now is a good time to sort out my plane.

The states so far have been static, since the user stories never called for them to change, just be reported on.  But it looks daft during the feature tests.  However I'm struggling to change them with internal methods I've written?  Do I need to use attr_accessor to access the method writers?  I thought any class could always access its own methods and variables, including to set them, even without an attr_writer.

Here is the code I've got in my plane class so far:
```
def initialize
    @landed = true
    @in_airport = true
    @cleared = false
  end

  def has_landed?
    landed
  end

  def takeoff
    landed = false
  end

  def in_airport?
    in_airport
  end

  def fly_away
    in_airport = false
  end

  def cleared
    cleared = true
    fly_away if cleared
    takeoff if cleared
  end
```

Here are the test results:

Failures:

  1) Plane#in_airport should say the plane has left the airport
     Failure/Error: expect(plane.in_airport?).to be(false)

       expected false
            got true
     # ./spec/plane_spec.rb:17:in `block (3 levels) in <top (required)>'

  2) Plane#cleared says the plane is cleared
     Failure/Error: expect(plane.cleared).to be(true)

       expected true
            got false
     # ./spec/plane_spec.rb:24:in `block (3 levels) in <top (required)>'

  3) Plane#cleared sets landed to false
     Failure/Error: expect(plane.has_landed?).to be(false)

       expected false
            got true
     # ./spec/plane_spec.rb:29:in `block (3 levels) in <top (required)>'

  4) Plane#cleared sets in_airport to false
     Failure/Error: expect(plane.in_airport?).to be(false)

       expected false
            got true
     # ./spec/plane_spec.rb:34:in `block (3 levels) in <top (required)>'
```

**Comment by chweeks** [comment] 2016-01-24 21:49
Within your methods you will have to reference your instance variables with an @. e.g @landed = true.
Then when you call plane.landed it will return true.

**Comment by leggsimon** [comment] 2016-01-25 22:54
> However I'm struggling to change them with internal methods I've written? Do I need to use attr_accessor to access the method writers? I thought any class could always access its own methods and variables, including to set them, even without an attr_writer.

As @chweeks says, to access the variable `landed` in your `cleared` method you will need to use the instance variable `@landed` _or_ you can use an `attr_accessor :landed`

The issue is that within your `cleared` method, you are setting a variable `cleared` (this is confusing by the way), however the variable is only in scope within that method. None of the rest of the class or it's methods have any knowledge of it.
```ruby
  def cleared
    cleared = true
    fly_away if cleared
    takeoff if cleared
  end
```
I'm not sure I see why you're doing the `if`s as well?

```ruby
  def cleared
    @sunny = true #just used sunny as an example, I assume by cleared you mean weather cleared?
    takeoff
    fly_away
  end
```
There is a principle/rule/good practice _(delete as appropriate)_ called [tell don't ask](https://robots.thoughtbot.com/tell-dont-ask). _**Tell**_ your program what to do when the weather has cleared.

**Comment by sjmog** [comment] 2016-02-10 15:50
Awesome answer @leggsimon - spot-on

**Closed by sjmog** 2016-02-10 15:50 UTC
